ingredients = {
    "kurczak": ["kurczak","kurczaka"],
    "bulion" : ["bulion","bulionu","bulionu/rosołu","wywaru/bulionu"],
    "cebula":['cebule', 'cebul', 'cebula', 'cebulek', 'cebulą', 'cebulki', 'cebulka', 'cebuli'],
    "dynia":['dyni','dynia'],
    "sól":['sól','soli'],
    "marchew":['marchewek', 'marchewki', 'marchew', 'marchwi', 'marchewka'],
    "wołowina":['wołowiny', 'wołowy', 'wołowina', 'wołowe', 'wołowej', 'wołowa', 'wołowego'],
    "mąka":['mąki', 'mąki/skrobi', 'mąka'],
    "pomidor":['pomidorowy', 'pomidorki', 'pomidorków', 'pomidor', 'pomidorowej', 'pomidorami', 'pomidorowego', 'pomidora', 'pomidorów', 'pomidory'],
    "por":['por', 'pora', 'pory'],
    "ziemniak":['ziemniaków', 'ziemniak', 'ziemniaki'],
    "jajko":['jajka', 'jaj', 'jajek', 'jajko', 'jaja'],
    "ser":['ser', 'serek', 'sera', 'sery', 'serka'],
    "skrobia":['skrobi', 'skrobia'],
    "burak":['buraczki', 'buraczkami', 'buraczków', 'buraków', 'buraki'],
    "pomarańcz":['pomarańczy',"pomarańcza"],
    "orzechy":['orzechy', 'orzechów', 'orzechowe'],
    "sałata":['sałatkowego', 'sałaty', 'sałata', 'sałatkowy', 'sałat'],
    "kiełbasa":['kiełbas', 'kiełbasa', 'kiełbasy'],
    "śmietana":['śmietanki', 'śmietana', 'śmietanką', 'śmietany', 'śmietanka'],
    "szczypior":['szczypiorem', 'szczypior', 'szczypiorek', 'szczypioru', 'szczypiorku', 'szczypiorkiem'],
    "twaróg":['twaróg', 'twarde', 'twarogu'],
    "olej":['olej', 'oleju'],
    "boczek":["boczku","boczek"],
    "makaron":['makaronie', 'makaronu', 'makaronowe', 'makaron'],
    "czosnek":['czosnek', 'czosnku', 'czosnkowej'],
    "masło":['masła', 'masło'],
    "jabłko":['jabłko', 'jabłka'],
    "papryka":['papryki', 'papryczki', 'papryk', 'papryka', 'papryczka', 'papryką'],
    "pieprz":['pieprzu', 'pieprz'],
    "ocet":['octu', 'octem',"ocet"],
    "mleko":['mleka', 'mleko'],
    "wieprzowiny":['wieprzowego', 'wieprzowy', 'wieprzowina', 'wieprzowej', 'wieprzowe', 'wieprzowa', 'wieprzowych', 'wieprzowiny'],
    "cukier":['cukrowej', 'cukru', 'cukrowego', 'cukrem','cukier'],
    "oliwa":['oliwa', 'oliwy', 'oliwek'],
    "woda":['woda', 'wody'],
    "pieczarki":['pieczarek', 'pieczarki'],
    "cytryna":['cytrynowej', 'cytryna', 'cytryny'],
    "cukinia":['cukinie', 'cukinii', 'cukinia'],
    "chilli":['chilli'],
    "pasta":['pasta', 'pasty'],
    "drożdże":['drożdże', 'drożdży'],
    "parmezan":['parmezanu', 'parmezan'],
    "pietruszki":['pietruszka', 'pietruszki'],
    "kapusty":['kapusty', 'kapustki', 'kapusta'],
    "soja":['sojowy', 'sojowego', 'sojowych'],
    "majonez":['majonezu', 'majonezowy'],
    "koperek":['koperku', 'koperek'],
    "seler":['selera', 'seler'],
    "rzodkiewka":['rzodkwi', 'rzodkiewek', 'rzodkiewki', 'rzodkiew'],
    "ryż":['ryż', 'ryżu', 'ryżowa', 'ryżowego', 'ryżowe', 'ryżowej'],
    "schab":['schab', 'schabu', 'schabowe'],
    "musztarda":['musztardy', 'musztarda'],
    "szynka":["szynki","szynka"]
}